CONSTANT(SPACE, 0x20);//[space]
CONSTANT(SCOLON, 0x3B);//;
CONSTANT(COMMA, 0x2C);//,
CONSTANT(EQUALS, 0x3D);//=
CONSTANT(QUOTE, 0x22);//"
CONSTANT(PCT, 0x25); //%
CONSTANT(LEFT, 0x5B); //[
CONSTANT(RIGHT, 0x5D); //]
CONSTANT(AMP, 0x26); //&
CONSTANT(PLUS, 0x2B); //+
CONSTANT(INT_START, 0x30);//0
CONSTANT(INT_END, 0x39); //10
CONSTANT(MAX_INDEX, Math.pow(2, 30) - 2);
CONSTANT(MAX_KEY_DEPTH, 12);

CONSTANT(CERTAINLY_NOT_NESTED, false);
CONSTANT(MIGHT_BE_NESTED, true);

CONSTANT(MAX_ASCII, 0x7F);
